server:
  port: 8081
  servlet:
    context-path: /resource-server

####### resource server configuration properties
spring:
  jpa:
    defer-datasource-initialization: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://6df0-2601-646-8100-5160-3971-1d10-538c-2aa7.ngrok.io/auth/realms/baeldung
          jwk-set-uri: https://6df0-2601-646-8100-5160-3971-1d10-538c-2aa7.ngrok.io/auth/realms/baeldung/protocol/openid-connect/certs